# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.payment import payment_pb2 as protos_dot_payment_dot_payment__pb2


class PaymentServiceStub(object):
    """═══════════════════════════════════════════════════════════════════════════
    PAYMENT SERVICE

    Manages payments, wallets, refunds, payouts, and payment methods for
    VeterPlan's veterinary home visits marketplace.

    Integrates with Wompi (Colombia) for card/Nequi processing.
    Provides wallet functionality for instant refunds and split payments.

    Depends on: Appointment Service (payment lifecycle triggers)
    Called by: Appointment Service, API Gateway, Admin
    ═══════════════════════════════════════════════════════════════════════════

    ─── PAYMENT LIFECYCLE (10 RPCs) ───
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePayment = channel.unary_unary(
                '/payment.PaymentService/CreatePayment',
                request_serializer=protos_dot_payment_dot_payment__pb2.CreatePaymentRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
                )
        self.AuthorizePayment = channel.unary_unary(
                '/payment.PaymentService/AuthorizePayment',
                request_serializer=protos_dot_payment_dot_payment__pb2.AuthorizePaymentRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
                )
        self.CapturePayment = channel.unary_unary(
                '/payment.PaymentService/CapturePayment',
                request_serializer=protos_dot_payment_dot_payment__pb2.CapturePaymentRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
                )
        self.VoidPayment = channel.unary_unary(
                '/payment.PaymentService/VoidPayment',
                request_serializer=protos_dot_payment_dot_payment__pb2.VoidPaymentRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
                )
        self.RefundPayment = channel.unary_unary(
                '/payment.PaymentService/RefundPayment',
                request_serializer=protos_dot_payment_dot_payment__pb2.RefundPaymentRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.RefundResponse.FromString,
                )
        self.ChargeNoShowFee = channel.unary_unary(
                '/payment.PaymentService/ChargeNoShowFee',
                request_serializer=protos_dot_payment_dot_payment__pb2.ChargeNoShowFeeRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
                )
        self.AddTip = channel.unary_unary(
                '/payment.PaymentService/AddTip',
                request_serializer=protos_dot_payment_dot_payment__pb2.AddTipRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
                )
        self.GetPayment = channel.unary_unary(
                '/payment.PaymentService/GetPayment',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetPaymentRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
                )
        self.GetPaymentByAppointment = channel.unary_unary(
                '/payment.PaymentService/GetPaymentByAppointment',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetPaymentByAppointmentRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
                )
        self.GetRefunds = channel.unary_unary(
                '/payment.PaymentService/GetRefunds',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetRefundsRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.RefundsResponse.FromString,
                )
        self.CreateWallet = channel.unary_unary(
                '/payment.PaymentService/CreateWallet',
                request_serializer=protos_dot_payment_dot_payment__pb2.CreateWalletRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
                )
        self.GetWallet = channel.unary_unary(
                '/payment.PaymentService/GetWallet',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetWalletRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
                )
        self.GetWalletTransactions = channel.unary_unary(
                '/payment.PaymentService/GetWalletTransactions',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetWalletTransactionsRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.WalletTransactionsResponse.FromString,
                )
        self.CreditWallet = channel.unary_unary(
                '/payment.PaymentService/CreditWallet',
                request_serializer=protos_dot_payment_dot_payment__pb2.CreditWalletRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
                )
        self.GetBalance = channel.unary_unary(
                '/payment.PaymentService/GetBalance',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.BalanceResponse.FromString,
                )
        self.FreezeWallet = channel.unary_unary(
                '/payment.PaymentService/FreezeWallet',
                request_serializer=protos_dot_payment_dot_payment__pb2.FreezeWalletRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
                )
        self.UnfreezeWallet = channel.unary_unary(
                '/payment.PaymentService/UnfreezeWallet',
                request_serializer=protos_dot_payment_dot_payment__pb2.UnfreezeWalletRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
                )
        self.AddPaymentMethod = channel.unary_unary(
                '/payment.PaymentService/AddPaymentMethod',
                request_serializer=protos_dot_payment_dot_payment__pb2.AddPaymentMethodRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentMethodResponse.FromString,
                )
        self.GetPaymentMethods = channel.unary_unary(
                '/payment.PaymentService/GetPaymentMethods',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetPaymentMethodsRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentMethodsResponse.FromString,
                )
        self.RemovePaymentMethod = channel.unary_unary(
                '/payment.PaymentService/RemovePaymentMethod',
                request_serializer=protos_dot_payment_dot_payment__pb2.RemovePaymentMethodRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PaymentMethodResponse.FromString,
                )
        self.RequestPayout = channel.unary_unary(
                '/payment.PaymentService/RequestPayout',
                request_serializer=protos_dot_payment_dot_payment__pb2.RequestPayoutRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PayoutResponse.FromString,
                )
        self.GetPayoutHistory = channel.unary_unary(
                '/payment.PaymentService/GetPayoutHistory',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetPayoutHistoryRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.PayoutHistoryResponse.FromString,
                )
        self.AddBankAccount = channel.unary_unary(
                '/payment.PaymentService/AddBankAccount',
                request_serializer=protos_dot_payment_dot_payment__pb2.AddBankAccountRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.BankAccountResponse.FromString,
                )
        self.GetBankAccounts = channel.unary_unary(
                '/payment.PaymentService/GetBankAccounts',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetBankAccountsRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.BankAccountsResponse.FromString,
                )
        self.GetVetEarnings = channel.unary_unary(
                '/payment.PaymentService/GetVetEarnings',
                request_serializer=protos_dot_payment_dot_payment__pb2.GetVetEarningsRequest.SerializeToString,
                response_deserializer=protos_dot_payment_dot_payment__pb2.VetEarningsResponse.FromString,
                )


class PaymentServiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════════
    PAYMENT SERVICE

    Manages payments, wallets, refunds, payouts, and payment methods for
    VeterPlan's veterinary home visits marketplace.

    Integrates with Wompi (Colombia) for card/Nequi processing.
    Provides wallet functionality for instant refunds and split payments.

    Depends on: Appointment Service (payment lifecycle triggers)
    Called by: Appointment Service, API Gateway, Admin
    ═══════════════════════════════════════════════════════════════════════════

    ─── PAYMENT LIFECYCLE (10 RPCs) ───
    """

    def CreatePayment(self, request, context):
        """Create a PENDING payment when appointment is requested. No money moves.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizePayment(self, request, context):
        """Pre-authorize payment (Wompi preauth + wallet HOLD). Called when vet accepts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CapturePayment(self, request, context):
        """Capture authorized payment. Called when appointment completes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoidPayment(self, request, context):
        """Void/release pre-authorization without charging. Called on cancel/expire pre-capture.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundPayment(self, request, context):
        """Process refund with client-chosen destination (WALLET/GATEWAY/MIXED).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChargeNoShowFee(self, request, context):
        """Charge no-show fee (30% capture + 70% void + partial refund).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTip(self, request, context):
        """Add tip post-appointment. Goes to vet wallet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayment(self, request, context):
        """Get payment by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentByAppointment(self, request, context):
        """Get payment by appointment ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRefunds(self, request, context):
        """Get refunds for a payment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWallet(self, request, context):
        """─── WALLET (7 RPCs) ───

        Create wallet for new user (called by Profile Service on profile creation).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWallet(self, request, context):
        """Get wallet with balance info.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWalletTransactions(self, request, context):
        """Get wallet transaction history with pagination and filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreditWallet(self, request, context):
        """Credit wallet (refund, promo, referral, compensation). Internal/Admin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Get balance only (lightweight for UI header).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreezeWallet(self, request, context):
        """Freeze wallet (fraud prevention).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnfreezeWallet(self, request, context):
        """Unfreeze wallet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPaymentMethod(self, request, context):
        """─── PAYMENT METHODS (3 RPCs) ───

        Add tokenized card/Nequi via Wompi.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentMethods(self, request, context):
        """List active payment methods for a client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePaymentMethod(self, request, context):
        """Soft-delete a payment method.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPayout(self, request, context):
        """─── PAYOUTS (2 RPCs) ───

        Vet requests payout. Calculates earnings and transfers via Wompi.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayoutHistory(self, request, context):
        """Get payout history for a vet with pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBankAccount(self, request, context):
        """─── BANK ACCOUNTS & EARNINGS (3 RPCs) ───

        Register vet bank account (encrypted AES-256-GCM).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBankAccounts(self, request, context):
        """List vet bank accounts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetEarnings(self, request, context):
        """Get vet earnings summary by period.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePayment,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.CreatePaymentRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'AuthorizePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizePayment,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.AuthorizePaymentRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'CapturePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.CapturePayment,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.CapturePaymentRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'VoidPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.VoidPayment,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.VoidPaymentRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'RefundPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundPayment,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.RefundPaymentRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.RefundResponse.SerializeToString,
            ),
            'ChargeNoShowFee': grpc.unary_unary_rpc_method_handler(
                    servicer.ChargeNoShowFee,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.ChargeNoShowFeeRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'AddTip': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTip,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.AddTipRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'GetPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayment,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetPaymentRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'GetPaymentByAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentByAppointment,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetPaymentByAppointmentRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'GetRefunds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRefunds,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetRefundsRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.RefundsResponse.SerializeToString,
            ),
            'CreateWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWallet,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.CreateWalletRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.WalletResponse.SerializeToString,
            ),
            'GetWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWallet,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetWalletRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.WalletResponse.SerializeToString,
            ),
            'GetWalletTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWalletTransactions,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetWalletTransactionsRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.WalletTransactionsResponse.SerializeToString,
            ),
            'CreditWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreditWallet,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.CreditWalletRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.WalletResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetBalanceRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.BalanceResponse.SerializeToString,
            ),
            'FreezeWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.FreezeWallet,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.FreezeWalletRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.WalletResponse.SerializeToString,
            ),
            'UnfreezeWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.UnfreezeWallet,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.UnfreezeWalletRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.WalletResponse.SerializeToString,
            ),
            'AddPaymentMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPaymentMethod,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.AddPaymentMethodRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentMethodResponse.SerializeToString,
            ),
            'GetPaymentMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentMethods,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetPaymentMethodsRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentMethodsResponse.SerializeToString,
            ),
            'RemovePaymentMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePaymentMethod,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.RemovePaymentMethodRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PaymentMethodResponse.SerializeToString,
            ),
            'RequestPayout': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPayout,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.RequestPayoutRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PayoutResponse.SerializeToString,
            ),
            'GetPayoutHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayoutHistory,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetPayoutHistoryRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.PayoutHistoryResponse.SerializeToString,
            ),
            'AddBankAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBankAccount,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.AddBankAccountRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.BankAccountResponse.SerializeToString,
            ),
            'GetBankAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBankAccounts,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetBankAccountsRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.BankAccountsResponse.SerializeToString,
            ),
            'GetVetEarnings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetEarnings,
                    request_deserializer=protos_dot_payment_dot_payment__pb2.GetVetEarningsRequest.FromString,
                    response_serializer=protos_dot_payment_dot_payment__pb2.VetEarningsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """═══════════════════════════════════════════════════════════════════════════
    PAYMENT SERVICE

    Manages payments, wallets, refunds, payouts, and payment methods for
    VeterPlan's veterinary home visits marketplace.

    Integrates with Wompi (Colombia) for card/Nequi processing.
    Provides wallet functionality for instant refunds and split payments.

    Depends on: Appointment Service (payment lifecycle triggers)
    Called by: Appointment Service, API Gateway, Admin
    ═══════════════════════════════════════════════════════════════════════════

    ─── PAYMENT LIFECYCLE (10 RPCs) ───
    """

    @staticmethod
    def CreatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/CreatePayment',
            protos_dot_payment_dot_payment__pb2.CreatePaymentRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AuthorizePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/AuthorizePayment',
            protos_dot_payment_dot_payment__pb2.AuthorizePaymentRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CapturePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/CapturePayment',
            protos_dot_payment_dot_payment__pb2.CapturePaymentRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VoidPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/VoidPayment',
            protos_dot_payment_dot_payment__pb2.VoidPaymentRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefundPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/RefundPayment',
            protos_dot_payment_dot_payment__pb2.RefundPaymentRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.RefundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChargeNoShowFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/ChargeNoShowFee',
            protos_dot_payment_dot_payment__pb2.ChargeNoShowFeeRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddTip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/AddTip',
            protos_dot_payment_dot_payment__pb2.AddTipRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetPayment',
            protos_dot_payment_dot_payment__pb2.GetPaymentRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPaymentByAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetPaymentByAppointment',
            protos_dot_payment_dot_payment__pb2.GetPaymentByAppointmentRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRefunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetRefunds',
            protos_dot_payment_dot_payment__pb2.GetRefundsRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.RefundsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/CreateWallet',
            protos_dot_payment_dot_payment__pb2.CreateWalletRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetWallet',
            protos_dot_payment_dot_payment__pb2.GetWalletRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWalletTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetWalletTransactions',
            protos_dot_payment_dot_payment__pb2.GetWalletTransactionsRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.WalletTransactionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreditWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/CreditWallet',
            protos_dot_payment_dot_payment__pb2.CreditWalletRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetBalance',
            protos_dot_payment_dot_payment__pb2.GetBalanceRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.BalanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FreezeWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/FreezeWallet',
            protos_dot_payment_dot_payment__pb2.FreezeWalletRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnfreezeWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/UnfreezeWallet',
            protos_dot_payment_dot_payment__pb2.UnfreezeWalletRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.WalletResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddPaymentMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/AddPaymentMethod',
            protos_dot_payment_dot_payment__pb2.AddPaymentMethodRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPaymentMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetPaymentMethods',
            protos_dot_payment_dot_payment__pb2.GetPaymentMethodsRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentMethodsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemovePaymentMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/RemovePaymentMethod',
            protos_dot_payment_dot_payment__pb2.RemovePaymentMethodRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PaymentMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestPayout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/RequestPayout',
            protos_dot_payment_dot_payment__pb2.RequestPayoutRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PayoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPayoutHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetPayoutHistory',
            protos_dot_payment_dot_payment__pb2.GetPayoutHistoryRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.PayoutHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBankAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/AddBankAccount',
            protos_dot_payment_dot_payment__pb2.AddBankAccountRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.BankAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBankAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetBankAccounts',
            protos_dot_payment_dot_payment__pb2.GetBankAccountsRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.BankAccountsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVetEarnings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/GetVetEarnings',
            protos_dot_payment_dot_payment__pb2.GetVetEarningsRequest.SerializeToString,
            protos_dot_payment_dot_payment__pb2.VetEarningsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
