# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from profile import client_profile_pb2 as profile_dot_client__profile__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in profile/client_profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientProfileServiceStub(object):
    """============================================================================
    CLIENT PROFILE SERVICE
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateClientProfile = channel.unary_unary(
                '/profile.ClientProfileService/CreateClientProfile',
                request_serializer=profile_dot_client__profile__pb2.CreateClientProfileRequest.SerializeToString,
                response_deserializer=profile_dot_client__profile__pb2.ClientProfileResponse.FromString,
                _registered_method=True)
        self.GetClientProfile = channel.unary_unary(
                '/profile.ClientProfileService/GetClientProfile',
                request_serializer=profile_dot_client__profile__pb2.GetClientProfileRequest.SerializeToString,
                response_deserializer=profile_dot_client__profile__pb2.ClientProfileResponse.FromString,
                _registered_method=True)
        self.UpdateClientProfile = channel.unary_unary(
                '/profile.ClientProfileService/UpdateClientProfile',
                request_serializer=profile_dot_client__profile__pb2.UpdateClientProfileRequest.SerializeToString,
                response_deserializer=profile_dot_client__profile__pb2.ClientProfileResponse.FromString,
                _registered_method=True)
        self.DeleteClientProfile = channel.unary_unary(
                '/profile.ClientProfileService/DeleteClientProfile',
                request_serializer=profile_dot_client__profile__pb2.DeleteClientProfileRequest.SerializeToString,
                response_deserializer=profile_dot_client__profile__pb2.DeleteClientProfileResponse.FromString,
                _registered_method=True)
        self.GetUserProfiles = channel.unary_unary(
                '/profile.ClientProfileService/GetUserProfiles',
                request_serializer=profile_dot_client__profile__pb2.GetUserProfilesRequest.SerializeToString,
                response_deserializer=profile_dot_client__profile__pb2.GetUserProfilesResponse.FromString,
                _registered_method=True)
        self.ListClientProfiles = channel.unary_unary(
                '/profile.ClientProfileService/ListClientProfiles',
                request_serializer=profile_dot_client__profile__pb2.ListClientProfilesRequest.SerializeToString,
                response_deserializer=profile_dot_client__profile__pb2.ListClientProfilesResponse.FromString,
                _registered_method=True)
        self.GenerateAvatarUploadUrl = channel.unary_unary(
                '/profile.ClientProfileService/GenerateAvatarUploadUrl',
                request_serializer=profile_dot_client__profile__pb2.GenerateAvatarUploadUrlRequest.SerializeToString,
                response_deserializer=profile_dot_client__profile__pb2.GenerateAvatarUploadUrlResponse.FromString,
                _registered_method=True)
        self.HardDeleteUserProfiles = channel.unary_unary(
                '/profile.ClientProfileService/HardDeleteUserProfiles',
                request_serializer=profile_dot_client__profile__pb2.HardDeleteUserProfilesRequest.SerializeToString,
                response_deserializer=profile_dot_client__profile__pb2.HardDeleteUserProfilesResponse.FromString,
                _registered_method=True)


class ClientProfileServiceServicer(object):
    """============================================================================
    CLIENT PROFILE SERVICE
    ============================================================================

    """

    def CreateClientProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClientProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteClientProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProfiles(self, request, context):
        """Multi-profile aggregation: returns both client and vet profile summaries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClientProfiles(self, request, context):
        """─── Admin: list all client profiles ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAvatarUploadUrl(self, request, context):
        """─── Avatar Upload ───
        Generate a presigned URL for direct avatar upload to R2 storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HardDeleteUserProfiles(self, request, context):
        """Hard delete all profiles for a user (testing utility)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateClientProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClientProfile,
                    request_deserializer=profile_dot_client__profile__pb2.CreateClientProfileRequest.FromString,
                    response_serializer=profile_dot_client__profile__pb2.ClientProfileResponse.SerializeToString,
            ),
            'GetClientProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientProfile,
                    request_deserializer=profile_dot_client__profile__pb2.GetClientProfileRequest.FromString,
                    response_serializer=profile_dot_client__profile__pb2.ClientProfileResponse.SerializeToString,
            ),
            'UpdateClientProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClientProfile,
                    request_deserializer=profile_dot_client__profile__pb2.UpdateClientProfileRequest.FromString,
                    response_serializer=profile_dot_client__profile__pb2.ClientProfileResponse.SerializeToString,
            ),
            'DeleteClientProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteClientProfile,
                    request_deserializer=profile_dot_client__profile__pb2.DeleteClientProfileRequest.FromString,
                    response_serializer=profile_dot_client__profile__pb2.DeleteClientProfileResponse.SerializeToString,
            ),
            'GetUserProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfiles,
                    request_deserializer=profile_dot_client__profile__pb2.GetUserProfilesRequest.FromString,
                    response_serializer=profile_dot_client__profile__pb2.GetUserProfilesResponse.SerializeToString,
            ),
            'ListClientProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClientProfiles,
                    request_deserializer=profile_dot_client__profile__pb2.ListClientProfilesRequest.FromString,
                    response_serializer=profile_dot_client__profile__pb2.ListClientProfilesResponse.SerializeToString,
            ),
            'GenerateAvatarUploadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAvatarUploadUrl,
                    request_deserializer=profile_dot_client__profile__pb2.GenerateAvatarUploadUrlRequest.FromString,
                    response_serializer=profile_dot_client__profile__pb2.GenerateAvatarUploadUrlResponse.SerializeToString,
            ),
            'HardDeleteUserProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.HardDeleteUserProfiles,
                    request_deserializer=profile_dot_client__profile__pb2.HardDeleteUserProfilesRequest.FromString,
                    response_serializer=profile_dot_client__profile__pb2.HardDeleteUserProfilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile.ClientProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('profile.ClientProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientProfileService(object):
    """============================================================================
    CLIENT PROFILE SERVICE
    ============================================================================

    """

    @staticmethod
    def CreateClientProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.ClientProfileService/CreateClientProfile',
            profile_dot_client__profile__pb2.CreateClientProfileRequest.SerializeToString,
            profile_dot_client__profile__pb2.ClientProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClientProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.ClientProfileService/GetClientProfile',
            profile_dot_client__profile__pb2.GetClientProfileRequest.SerializeToString,
            profile_dot_client__profile__pb2.ClientProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClientProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.ClientProfileService/UpdateClientProfile',
            profile_dot_client__profile__pb2.UpdateClientProfileRequest.SerializeToString,
            profile_dot_client__profile__pb2.ClientProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteClientProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.ClientProfileService/DeleteClientProfile',
            profile_dot_client__profile__pb2.DeleteClientProfileRequest.SerializeToString,
            profile_dot_client__profile__pb2.DeleteClientProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.ClientProfileService/GetUserProfiles',
            profile_dot_client__profile__pb2.GetUserProfilesRequest.SerializeToString,
            profile_dot_client__profile__pb2.GetUserProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClientProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.ClientProfileService/ListClientProfiles',
            profile_dot_client__profile__pb2.ListClientProfilesRequest.SerializeToString,
            profile_dot_client__profile__pb2.ListClientProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAvatarUploadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.ClientProfileService/GenerateAvatarUploadUrl',
            profile_dot_client__profile__pb2.GenerateAvatarUploadUrlRequest.SerializeToString,
            profile_dot_client__profile__pb2.GenerateAvatarUploadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HardDeleteUserProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.ClientProfileService/HardDeleteUserProfiles',
            profile_dot_client__profile__pb2.HardDeleteUserProfilesRequest.SerializeToString,
            profile_dot_client__profile__pb2.HardDeleteUserProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
