# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profile/profile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'profile/profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15profile/profile.proto\x12\x07profile\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x02\n\x07Profile\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x12\n\navatar_url\x18\x05 \x01(\t\x12\x0e\n\x06gender\x18\x06 \x01(\t\x12\x11\n\tbirthdate\x18\x07 \x01(\t\x12\x0e\n\x06locale\x18\x08 \x01(\t\x12\x10\n\x08timezone\x18\t \x01(\t\x12\x14\n\x0cis_completed\x18\n \x01(\x08\x12.\n\ncreated_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\'\n\x14\x43reateProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"$\n\x11GetProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\xa7\x02\n\x14UpdateProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\nfirst_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlast_name\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x17\n\navatar_url\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06gender\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x16\n\tbirthdate\x18\x06 \x01(\tH\x04\x88\x01\x01\x12\x13\n\x06locale\x18\x07 \x01(\tH\x05\x88\x01\x01\x12\x15\n\x08timezone\x18\x08 \x01(\tH\x06\x88\x01\x01\x42\r\n\x0b_first_nameB\x0c\n\n_last_nameB\r\n\x0b_avatar_urlB\t\n\x07_genderB\x0c\n\n_birthdateB\t\n\x07_localeB\x0b\n\t_timezone\"4\n\x0fProfileResponse\x12!\n\x07profile\x18\x01 \x01(\x0b\x32\x10.profile.Profile2\xe8\x01\n\x0eProfileService\x12H\n\rCreateProfile\x12\x1d.profile.CreateProfileRequest\x1a\x18.profile.ProfileResponse\x12\x42\n\nGetProfile\x12\x1a.profile.GetProfileRequest\x1a\x18.profile.ProfileResponse\x12H\n\rUpdateProfile\x12\x1d.profile.UpdateProfileRequest\x1a\x18.profile.ProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile.profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILE']._serialized_start=68
  _globals['_PROFILE']._serialized_end=352
  _globals['_CREATEPROFILEREQUEST']._serialized_start=354
  _globals['_CREATEPROFILEREQUEST']._serialized_end=393
  _globals['_GETPROFILEREQUEST']._serialized_start=395
  _globals['_GETPROFILEREQUEST']._serialized_end=431
  _globals['_UPDATEPROFILEREQUEST']._serialized_start=434
  _globals['_UPDATEPROFILEREQUEST']._serialized_end=729
  _globals['_PROFILERESPONSE']._serialized_start=731
  _globals['_PROFILERESPONSE']._serialized_end=783
  _globals['_PROFILESERVICE']._serialized_start=786
  _globals['_PROFILESERVICE']._serialized_end=1018
# @@protoc_insertion_point(module_scope)
