# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.profile import vet_profile_pb2 as protos_dot_profile_dot_vet__profile__pb2


class VetProfileServiceStub(object):
    """============================================================================
    VET PROFILE SERVICE
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVetProfile = channel.unary_unary(
                '/profile.VetProfileService/CreateVetProfile',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.CreateVetProfileRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                )
        self.GetVetProfile = channel.unary_unary(
                '/profile.VetProfileService/GetVetProfile',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.GetVetProfileRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                )
        self.UpdateVetProfile = channel.unary_unary(
                '/profile.VetProfileService/UpdateVetProfile',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                )
        self.DeleteVetProfile = channel.unary_unary(
                '/profile.VetProfileService/DeleteVetProfile',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileResponse.FromString,
                )
        self.UpdateVetProfileStatus = channel.unary_unary(
                '/profile.VetProfileService/UpdateVetProfileStatus',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileStatusRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                )


class VetProfileServiceServicer(object):
    """============================================================================
    VET PROFILE SERVICE
    ============================================================================

    """

    def CreateVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVetProfileStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VetProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVetProfile,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.CreateVetProfileRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'GetVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetProfile,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.GetVetProfileRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'UpdateVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVetProfile,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'DeleteVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVetProfile,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileResponse.SerializeToString,
            ),
            'UpdateVetProfileStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVetProfileStatus,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileStatusRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile.VetProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VetProfileService(object):
    """============================================================================
    VET PROFILE SERVICE
    ============================================================================

    """

    @staticmethod
    def CreateVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/CreateVetProfile',
            protos_dot_profile_dot_vet__profile__pb2.CreateVetProfileRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/GetVetProfile',
            protos_dot_profile_dot_vet__profile__pb2.GetVetProfileRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/UpdateVetProfile',
            protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/DeleteVetProfile',
            protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVetProfileStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/UpdateVetProfileStatus',
            protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileStatusRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
