# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from profile import vet_profile_pb2 as profile_dot_vet__profile__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in profile/vet_profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VetProfileServiceStub(object):
    """============================================================================
    VET PROFILE SERVICE
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVetProfile = channel.unary_unary(
                '/profile.VetProfileService/CreateVetProfile',
                request_serializer=profile_dot_vet__profile__pb2.CreateVetProfileRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                _registered_method=True)
        self.GetVetProfile = channel.unary_unary(
                '/profile.VetProfileService/GetVetProfile',
                request_serializer=profile_dot_vet__profile__pb2.GetVetProfileRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                _registered_method=True)
        self.UpdateVetProfile = channel.unary_unary(
                '/profile.VetProfileService/UpdateVetProfile',
                request_serializer=profile_dot_vet__profile__pb2.UpdateVetProfileRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                _registered_method=True)
        self.DeleteVetProfile = channel.unary_unary(
                '/profile.VetProfileService/DeleteVetProfile',
                request_serializer=profile_dot_vet__profile__pb2.DeleteVetProfileRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.DeleteVetProfileResponse.FromString,
                _registered_method=True)
        self.UpdateVetProfileStatus = channel.unary_unary(
                '/profile.VetProfileService/UpdateVetProfileStatus',
                request_serializer=profile_dot_vet__profile__pb2.UpdateVetProfileStatusRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                _registered_method=True)
        self.SetServicePrice = channel.unary_unary(
                '/profile.VetProfileService/SetServicePrice',
                request_serializer=profile_dot_vet__profile__pb2.SetServicePriceRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.ServicePriceResponse.FromString,
                _registered_method=True)
        self.GetVetServicePrices = channel.unary_unary(
                '/profile.VetProfileService/GetVetServicePrices',
                request_serializer=profile_dot_vet__profile__pb2.GetVetServicePricesRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.VetServicePricesResponse.FromString,
                _registered_method=True)
        self.GetVetPriceForService = channel.unary_unary(
                '/profile.VetProfileService/GetVetPriceForService',
                request_serializer=profile_dot_vet__profile__pb2.GetVetPriceForServiceRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.ServicePriceResponse.FromString,
                _registered_method=True)
        self.RemoveServicePrice = channel.unary_unary(
                '/profile.VetProfileService/RemoveServicePrice',
                request_serializer=profile_dot_vet__profile__pb2.RemoveServicePriceRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.RemoveServicePriceResponse.FromString,
                _registered_method=True)
        self.GetVetsByService = channel.unary_unary(
                '/profile.VetProfileService/GetVetsByService',
                request_serializer=profile_dot_vet__profile__pb2.GetVetsByServiceRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.VetsByServiceResponse.FromString,
                _registered_method=True)
        self.GetServiceTypePriceRanges = channel.unary_unary(
                '/profile.VetProfileService/GetServiceTypePriceRanges',
                request_serializer=profile_dot_vet__profile__pb2.GetServiceTypePriceRangesRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.ServiceTypePriceRangesResponse.FromString,
                _registered_method=True)
        self.SetWorkingHours = channel.unary_unary(
                '/profile.VetProfileService/SetWorkingHours',
                request_serializer=profile_dot_vet__profile__pb2.SetWorkingHoursRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.WorkingHoursResponse.FromString,
                _registered_method=True)
        self.SetBulkWorkingHours = channel.unary_unary(
                '/profile.VetProfileService/SetBulkWorkingHours',
                request_serializer=profile_dot_vet__profile__pb2.SetBulkWorkingHoursRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.FromString,
                _registered_method=True)
        self.GetWorkingHours = channel.unary_unary(
                '/profile.VetProfileService/GetWorkingHours',
                request_serializer=profile_dot_vet__profile__pb2.GetWorkingHoursRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.FromString,
                _registered_method=True)
        self.RemoveWorkingDay = channel.unary_unary(
                '/profile.VetProfileService/RemoveWorkingDay',
                request_serializer=profile_dot_vet__profile__pb2.RemoveWorkingDayRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.RemoveWorkingDayResponse.FromString,
                _registered_method=True)
        self.AddTimeOff = channel.unary_unary(
                '/profile.VetProfileService/AddTimeOff',
                request_serializer=profile_dot_vet__profile__pb2.AddTimeOffRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.TimeOffResponse.FromString,
                _registered_method=True)
        self.GetTimeOff = channel.unary_unary(
                '/profile.VetProfileService/GetTimeOff',
                request_serializer=profile_dot_vet__profile__pb2.GetTimeOffRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.TimeOffListResponse.FromString,
                _registered_method=True)
        self.RemoveTimeOff = channel.unary_unary(
                '/profile.VetProfileService/RemoveTimeOff',
                request_serializer=profile_dot_vet__profile__pb2.RemoveTimeOffRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.RemoveTimeOffResponse.FromString,
                _registered_method=True)
        self.CheckVetAvailability = channel.unary_unary(
                '/profile.VetProfileService/CheckVetAvailability',
                request_serializer=profile_dot_vet__profile__pb2.CheckVetAvailabilityRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.CheckVetAvailabilityResponse.FromString,
                _registered_method=True)
        self.CheckBulkVetAvailability = channel.unary_unary(
                '/profile.VetProfileService/CheckBulkVetAvailability',
                request_serializer=profile_dot_vet__profile__pb2.CheckBulkVetAvailabilityRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.BulkVetAvailabilityResponse.FromString,
                _registered_method=True)
        self.GetVetAvailableSlots = channel.unary_unary(
                '/profile.VetProfileService/GetVetAvailableSlots',
                request_serializer=profile_dot_vet__profile__pb2.GetVetAvailableSlotsRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.VetAvailableSlotsResponse.FromString,
                _registered_method=True)
        self.IncrementCancellationStrike = channel.unary_unary(
                '/profile.VetProfileService/IncrementCancellationStrike',
                request_serializer=profile_dot_vet__profile__pb2.IncrementCancellationStrikeRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.IncrementCancellationStrikeResponse.FromString,
                _registered_method=True)
        self.UpdateVetRating = channel.unary_unary(
                '/profile.VetProfileService/UpdateVetRating',
                request_serializer=profile_dot_vet__profile__pb2.UpdateVetRatingRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.UpdateVetRatingResponse.FromString,
                _registered_method=True)
        self.ListVetProfiles = channel.unary_unary(
                '/profile.VetProfileService/ListVetProfiles',
                request_serializer=profile_dot_vet__profile__pb2.ListVetProfilesRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.ListVetProfilesResponse.FromString,
                _registered_method=True)
        self.GenerateAvatarUploadUrl = channel.unary_unary(
                '/profile.VetProfileService/GenerateAvatarUploadUrl',
                request_serializer=profile_dot_vet__profile__pb2.GenerateVetAvatarUploadUrlRequest.SerializeToString,
                response_deserializer=profile_dot_vet__profile__pb2.GenerateVetAvatarUploadUrlResponse.FromString,
                _registered_method=True)


class VetProfileServiceServicer(object):
    """============================================================================
    VET PROFILE SERVICE
    ============================================================================

    """

    def CreateVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVetProfileStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetServicePrice(self, request, context):
        """─── Vet Service Pricing ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetServicePrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetPriceForService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveServicePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetsByService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceTypePriceRanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWorkingHours(self, request, context):
        """─── Working Hours ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBulkWorkingHours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkingHours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveWorkingDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTimeOff(self, request, context):
        """─── Time Off ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTimeOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckVetAvailability(self, request, context):
        """─── Availability Check (inter-service, called by Appointment Service) ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBulkVetAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetAvailableSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementCancellationStrike(self, request, context):
        """─── Cancellation Strikes (inter-service, called by Appointment Service) ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVetRating(self, request, context):
        """─── Rating (S2-4) — called by Appointment Service on SubmitReview ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVetProfiles(self, request, context):
        """─── Admin: list all vet profiles ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAvatarUploadUrl(self, request, context):
        """─── Avatar Upload ───
        Generate a presigned URL for direct avatar upload to R2 storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VetProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVetProfile,
                    request_deserializer=profile_dot_vet__profile__pb2.CreateVetProfileRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'GetVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetProfile,
                    request_deserializer=profile_dot_vet__profile__pb2.GetVetProfileRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'UpdateVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVetProfile,
                    request_deserializer=profile_dot_vet__profile__pb2.UpdateVetProfileRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'DeleteVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVetProfile,
                    request_deserializer=profile_dot_vet__profile__pb2.DeleteVetProfileRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.DeleteVetProfileResponse.SerializeToString,
            ),
            'UpdateVetProfileStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVetProfileStatus,
                    request_deserializer=profile_dot_vet__profile__pb2.UpdateVetProfileStatusRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'SetServicePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.SetServicePrice,
                    request_deserializer=profile_dot_vet__profile__pb2.SetServicePriceRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.ServicePriceResponse.SerializeToString,
            ),
            'GetVetServicePrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetServicePrices,
                    request_deserializer=profile_dot_vet__profile__pb2.GetVetServicePricesRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.VetServicePricesResponse.SerializeToString,
            ),
            'GetVetPriceForService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetPriceForService,
                    request_deserializer=profile_dot_vet__profile__pb2.GetVetPriceForServiceRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.ServicePriceResponse.SerializeToString,
            ),
            'RemoveServicePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveServicePrice,
                    request_deserializer=profile_dot_vet__profile__pb2.RemoveServicePriceRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.RemoveServicePriceResponse.SerializeToString,
            ),
            'GetVetsByService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetsByService,
                    request_deserializer=profile_dot_vet__profile__pb2.GetVetsByServiceRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.VetsByServiceResponse.SerializeToString,
            ),
            'GetServiceTypePriceRanges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceTypePriceRanges,
                    request_deserializer=profile_dot_vet__profile__pb2.GetServiceTypePriceRangesRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.ServiceTypePriceRangesResponse.SerializeToString,
            ),
            'SetWorkingHours': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWorkingHours,
                    request_deserializer=profile_dot_vet__profile__pb2.SetWorkingHoursRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.WorkingHoursResponse.SerializeToString,
            ),
            'SetBulkWorkingHours': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBulkWorkingHours,
                    request_deserializer=profile_dot_vet__profile__pb2.SetBulkWorkingHoursRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.SerializeToString,
            ),
            'GetWorkingHours': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkingHours,
                    request_deserializer=profile_dot_vet__profile__pb2.GetWorkingHoursRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.SerializeToString,
            ),
            'RemoveWorkingDay': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveWorkingDay,
                    request_deserializer=profile_dot_vet__profile__pb2.RemoveWorkingDayRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.RemoveWorkingDayResponse.SerializeToString,
            ),
            'AddTimeOff': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTimeOff,
                    request_deserializer=profile_dot_vet__profile__pb2.AddTimeOffRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.TimeOffResponse.SerializeToString,
            ),
            'GetTimeOff': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeOff,
                    request_deserializer=profile_dot_vet__profile__pb2.GetTimeOffRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.TimeOffListResponse.SerializeToString,
            ),
            'RemoveTimeOff': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTimeOff,
                    request_deserializer=profile_dot_vet__profile__pb2.RemoveTimeOffRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.RemoveTimeOffResponse.SerializeToString,
            ),
            'CheckVetAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckVetAvailability,
                    request_deserializer=profile_dot_vet__profile__pb2.CheckVetAvailabilityRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.CheckVetAvailabilityResponse.SerializeToString,
            ),
            'CheckBulkVetAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBulkVetAvailability,
                    request_deserializer=profile_dot_vet__profile__pb2.CheckBulkVetAvailabilityRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.BulkVetAvailabilityResponse.SerializeToString,
            ),
            'GetVetAvailableSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetAvailableSlots,
                    request_deserializer=profile_dot_vet__profile__pb2.GetVetAvailableSlotsRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.VetAvailableSlotsResponse.SerializeToString,
            ),
            'IncrementCancellationStrike': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementCancellationStrike,
                    request_deserializer=profile_dot_vet__profile__pb2.IncrementCancellationStrikeRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.IncrementCancellationStrikeResponse.SerializeToString,
            ),
            'UpdateVetRating': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVetRating,
                    request_deserializer=profile_dot_vet__profile__pb2.UpdateVetRatingRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.UpdateVetRatingResponse.SerializeToString,
            ),
            'ListVetProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVetProfiles,
                    request_deserializer=profile_dot_vet__profile__pb2.ListVetProfilesRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.ListVetProfilesResponse.SerializeToString,
            ),
            'GenerateAvatarUploadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAvatarUploadUrl,
                    request_deserializer=profile_dot_vet__profile__pb2.GenerateVetAvatarUploadUrlRequest.FromString,
                    response_serializer=profile_dot_vet__profile__pb2.GenerateVetAvatarUploadUrlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile.VetProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('profile.VetProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VetProfileService(object):
    """============================================================================
    VET PROFILE SERVICE
    ============================================================================

    """

    @staticmethod
    def CreateVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/CreateVetProfile',
            profile_dot_vet__profile__pb2.CreateVetProfileRequest.SerializeToString,
            profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/GetVetProfile',
            profile_dot_vet__profile__pb2.GetVetProfileRequest.SerializeToString,
            profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/UpdateVetProfile',
            profile_dot_vet__profile__pb2.UpdateVetProfileRequest.SerializeToString,
            profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/DeleteVetProfile',
            profile_dot_vet__profile__pb2.DeleteVetProfileRequest.SerializeToString,
            profile_dot_vet__profile__pb2.DeleteVetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVetProfileStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/UpdateVetProfileStatus',
            profile_dot_vet__profile__pb2.UpdateVetProfileStatusRequest.SerializeToString,
            profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetServicePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/SetServicePrice',
            profile_dot_vet__profile__pb2.SetServicePriceRequest.SerializeToString,
            profile_dot_vet__profile__pb2.ServicePriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVetServicePrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/GetVetServicePrices',
            profile_dot_vet__profile__pb2.GetVetServicePricesRequest.SerializeToString,
            profile_dot_vet__profile__pb2.VetServicePricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVetPriceForService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/GetVetPriceForService',
            profile_dot_vet__profile__pb2.GetVetPriceForServiceRequest.SerializeToString,
            profile_dot_vet__profile__pb2.ServicePriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveServicePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/RemoveServicePrice',
            profile_dot_vet__profile__pb2.RemoveServicePriceRequest.SerializeToString,
            profile_dot_vet__profile__pb2.RemoveServicePriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVetsByService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/GetVetsByService',
            profile_dot_vet__profile__pb2.GetVetsByServiceRequest.SerializeToString,
            profile_dot_vet__profile__pb2.VetsByServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceTypePriceRanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/GetServiceTypePriceRanges',
            profile_dot_vet__profile__pb2.GetServiceTypePriceRangesRequest.SerializeToString,
            profile_dot_vet__profile__pb2.ServiceTypePriceRangesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWorkingHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/SetWorkingHours',
            profile_dot_vet__profile__pb2.SetWorkingHoursRequest.SerializeToString,
            profile_dot_vet__profile__pb2.WorkingHoursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBulkWorkingHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/SetBulkWorkingHours',
            profile_dot_vet__profile__pb2.SetBulkWorkingHoursRequest.SerializeToString,
            profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkingHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/GetWorkingHours',
            profile_dot_vet__profile__pb2.GetWorkingHoursRequest.SerializeToString,
            profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveWorkingDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/RemoveWorkingDay',
            profile_dot_vet__profile__pb2.RemoveWorkingDayRequest.SerializeToString,
            profile_dot_vet__profile__pb2.RemoveWorkingDayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTimeOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/AddTimeOff',
            profile_dot_vet__profile__pb2.AddTimeOffRequest.SerializeToString,
            profile_dot_vet__profile__pb2.TimeOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/GetTimeOff',
            profile_dot_vet__profile__pb2.GetTimeOffRequest.SerializeToString,
            profile_dot_vet__profile__pb2.TimeOffListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTimeOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/RemoveTimeOff',
            profile_dot_vet__profile__pb2.RemoveTimeOffRequest.SerializeToString,
            profile_dot_vet__profile__pb2.RemoveTimeOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckVetAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/CheckVetAvailability',
            profile_dot_vet__profile__pb2.CheckVetAvailabilityRequest.SerializeToString,
            profile_dot_vet__profile__pb2.CheckVetAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBulkVetAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/CheckBulkVetAvailability',
            profile_dot_vet__profile__pb2.CheckBulkVetAvailabilityRequest.SerializeToString,
            profile_dot_vet__profile__pb2.BulkVetAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVetAvailableSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/GetVetAvailableSlots',
            profile_dot_vet__profile__pb2.GetVetAvailableSlotsRequest.SerializeToString,
            profile_dot_vet__profile__pb2.VetAvailableSlotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementCancellationStrike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/IncrementCancellationStrike',
            profile_dot_vet__profile__pb2.IncrementCancellationStrikeRequest.SerializeToString,
            profile_dot_vet__profile__pb2.IncrementCancellationStrikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVetRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/UpdateVetRating',
            profile_dot_vet__profile__pb2.UpdateVetRatingRequest.SerializeToString,
            profile_dot_vet__profile__pb2.UpdateVetRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVetProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/ListVetProfiles',
            profile_dot_vet__profile__pb2.ListVetProfilesRequest.SerializeToString,
            profile_dot_vet__profile__pb2.ListVetProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAvatarUploadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.VetProfileService/GenerateAvatarUploadUrl',
            profile_dot_vet__profile__pb2.GenerateVetAvatarUploadUrlRequest.SerializeToString,
            profile_dot_vet__profile__pb2.GenerateVetAvatarUploadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
