# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.profile import vet_profile_pb2 as protos_dot_profile_dot_vet__profile__pb2


class VetProfileServiceStub(object):
    """============================================================================
    VET PROFILE SERVICE
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVetProfile = channel.unary_unary(
                '/profile.VetProfileService/CreateVetProfile',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.CreateVetProfileRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                )
        self.GetVetProfile = channel.unary_unary(
                '/profile.VetProfileService/GetVetProfile',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.GetVetProfileRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                )
        self.UpdateVetProfile = channel.unary_unary(
                '/profile.VetProfileService/UpdateVetProfile',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                )
        self.DeleteVetProfile = channel.unary_unary(
                '/profile.VetProfileService/DeleteVetProfile',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileResponse.FromString,
                )
        self.UpdateVetProfileStatus = channel.unary_unary(
                '/profile.VetProfileService/UpdateVetProfileStatus',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileStatusRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
                )
        self.SetServicePrice = channel.unary_unary(
                '/profile.VetProfileService/SetServicePrice',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.SetServicePriceRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.ServicePriceResponse.FromString,
                )
        self.GetVetServicePrices = channel.unary_unary(
                '/profile.VetProfileService/GetVetServicePrices',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.GetVetServicePricesRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetServicePricesResponse.FromString,
                )
        self.GetVetPriceForService = channel.unary_unary(
                '/profile.VetProfileService/GetVetPriceForService',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.GetVetPriceForServiceRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.ServicePriceResponse.FromString,
                )
        self.RemoveServicePrice = channel.unary_unary(
                '/profile.VetProfileService/RemoveServicePrice',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.RemoveServicePriceRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.RemoveServicePriceResponse.FromString,
                )
        self.GetVetsByService = channel.unary_unary(
                '/profile.VetProfileService/GetVetsByService',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.GetVetsByServiceRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetsByServiceResponse.FromString,
                )
        self.SetWorkingHours = channel.unary_unary(
                '/profile.VetProfileService/SetWorkingHours',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.SetWorkingHoursRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.WorkingHoursResponse.FromString,
                )
        self.SetBulkWorkingHours = channel.unary_unary(
                '/profile.VetProfileService/SetBulkWorkingHours',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.SetBulkWorkingHoursRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.FromString,
                )
        self.GetWorkingHours = channel.unary_unary(
                '/profile.VetProfileService/GetWorkingHours',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.GetWorkingHoursRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.FromString,
                )
        self.RemoveWorkingDay = channel.unary_unary(
                '/profile.VetProfileService/RemoveWorkingDay',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.RemoveWorkingDayRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.RemoveWorkingDayResponse.FromString,
                )
        self.AddTimeOff = channel.unary_unary(
                '/profile.VetProfileService/AddTimeOff',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.AddTimeOffRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.TimeOffResponse.FromString,
                )
        self.GetTimeOff = channel.unary_unary(
                '/profile.VetProfileService/GetTimeOff',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.GetTimeOffRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.TimeOffListResponse.FromString,
                )
        self.RemoveTimeOff = channel.unary_unary(
                '/profile.VetProfileService/RemoveTimeOff',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.RemoveTimeOffRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.RemoveTimeOffResponse.FromString,
                )
        self.CheckVetAvailability = channel.unary_unary(
                '/profile.VetProfileService/CheckVetAvailability',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.CheckVetAvailabilityRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.CheckVetAvailabilityResponse.FromString,
                )
        self.GetVetAvailableSlots = channel.unary_unary(
                '/profile.VetProfileService/GetVetAvailableSlots',
                request_serializer=protos_dot_profile_dot_vet__profile__pb2.GetVetAvailableSlotsRequest.SerializeToString,
                response_deserializer=protos_dot_profile_dot_vet__profile__pb2.VetAvailableSlotsResponse.FromString,
                )


class VetProfileServiceServicer(object):
    """============================================================================
    VET PROFILE SERVICE
    ============================================================================

    """

    def CreateVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVetProfileStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetServicePrice(self, request, context):
        """─── Vet Service Pricing ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetServicePrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetPriceForService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveServicePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetsByService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWorkingHours(self, request, context):
        """─── Working Hours ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBulkWorkingHours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkingHours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveWorkingDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTimeOff(self, request, context):
        """─── Time Off ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTimeOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckVetAvailability(self, request, context):
        """─── Availability Check (inter-service, called by Appointment Service) ───
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetAvailableSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VetProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVetProfile,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.CreateVetProfileRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'GetVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetProfile,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.GetVetProfileRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'UpdateVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVetProfile,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'DeleteVetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVetProfile,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileResponse.SerializeToString,
            ),
            'UpdateVetProfileStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVetProfileStatus,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileStatusRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.SerializeToString,
            ),
            'SetServicePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.SetServicePrice,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.SetServicePriceRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.ServicePriceResponse.SerializeToString,
            ),
            'GetVetServicePrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetServicePrices,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.GetVetServicePricesRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetServicePricesResponse.SerializeToString,
            ),
            'GetVetPriceForService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetPriceForService,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.GetVetPriceForServiceRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.ServicePriceResponse.SerializeToString,
            ),
            'RemoveServicePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveServicePrice,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.RemoveServicePriceRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.RemoveServicePriceResponse.SerializeToString,
            ),
            'GetVetsByService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetsByService,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.GetVetsByServiceRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetsByServiceResponse.SerializeToString,
            ),
            'SetWorkingHours': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWorkingHours,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.SetWorkingHoursRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.WorkingHoursResponse.SerializeToString,
            ),
            'SetBulkWorkingHours': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBulkWorkingHours,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.SetBulkWorkingHoursRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.SerializeToString,
            ),
            'GetWorkingHours': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkingHours,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.GetWorkingHoursRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.SerializeToString,
            ),
            'RemoveWorkingDay': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveWorkingDay,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.RemoveWorkingDayRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.RemoveWorkingDayResponse.SerializeToString,
            ),
            'AddTimeOff': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTimeOff,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.AddTimeOffRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.TimeOffResponse.SerializeToString,
            ),
            'GetTimeOff': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeOff,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.GetTimeOffRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.TimeOffListResponse.SerializeToString,
            ),
            'RemoveTimeOff': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTimeOff,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.RemoveTimeOffRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.RemoveTimeOffResponse.SerializeToString,
            ),
            'CheckVetAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckVetAvailability,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.CheckVetAvailabilityRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.CheckVetAvailabilityResponse.SerializeToString,
            ),
            'GetVetAvailableSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetAvailableSlots,
                    request_deserializer=protos_dot_profile_dot_vet__profile__pb2.GetVetAvailableSlotsRequest.FromString,
                    response_serializer=protos_dot_profile_dot_vet__profile__pb2.VetAvailableSlotsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile.VetProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VetProfileService(object):
    """============================================================================
    VET PROFILE SERVICE
    ============================================================================

    """

    @staticmethod
    def CreateVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/CreateVetProfile',
            protos_dot_profile_dot_vet__profile__pb2.CreateVetProfileRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/GetVetProfile',
            protos_dot_profile_dot_vet__profile__pb2.GetVetProfileRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/UpdateVetProfile',
            protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/DeleteVetProfile',
            protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.DeleteVetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVetProfileStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/UpdateVetProfileStatus',
            protos_dot_profile_dot_vet__profile__pb2.UpdateVetProfileStatusRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetServicePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/SetServicePrice',
            protos_dot_profile_dot_vet__profile__pb2.SetServicePriceRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.ServicePriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVetServicePrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/GetVetServicePrices',
            protos_dot_profile_dot_vet__profile__pb2.GetVetServicePricesRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetServicePricesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVetPriceForService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/GetVetPriceForService',
            protos_dot_profile_dot_vet__profile__pb2.GetVetPriceForServiceRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.ServicePriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveServicePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/RemoveServicePrice',
            protos_dot_profile_dot_vet__profile__pb2.RemoveServicePriceRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.RemoveServicePriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVetsByService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/GetVetsByService',
            protos_dot_profile_dot_vet__profile__pb2.GetVetsByServiceRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetsByServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetWorkingHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/SetWorkingHours',
            protos_dot_profile_dot_vet__profile__pb2.SetWorkingHoursRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.WorkingHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetBulkWorkingHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/SetBulkWorkingHours',
            protos_dot_profile_dot_vet__profile__pb2.SetBulkWorkingHoursRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWorkingHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/GetWorkingHours',
            protos_dot_profile_dot_vet__profile__pb2.GetWorkingHoursRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.BulkWorkingHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveWorkingDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/RemoveWorkingDay',
            protos_dot_profile_dot_vet__profile__pb2.RemoveWorkingDayRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.RemoveWorkingDayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddTimeOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/AddTimeOff',
            protos_dot_profile_dot_vet__profile__pb2.AddTimeOffRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.TimeOffResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimeOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/GetTimeOff',
            protos_dot_profile_dot_vet__profile__pb2.GetTimeOffRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.TimeOffListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveTimeOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/RemoveTimeOff',
            protos_dot_profile_dot_vet__profile__pb2.RemoveTimeOffRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.RemoveTimeOffResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckVetAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/CheckVetAvailability',
            protos_dot_profile_dot_vet__profile__pb2.CheckVetAvailabilityRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.CheckVetAvailabilityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVetAvailableSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.VetProfileService/GetVetAvailableSlots',
            protos_dot_profile_dot_vet__profile__pb2.GetVetAvailableSlotsRequest.SerializeToString,
            protos_dot_profile_dot_vet__profile__pb2.VetAvailableSlotsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
