# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from constancia import constancia_pb2 as constancia_dot_constancia__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in constancia/constancia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConstanciaServiceStub(object):
    """═══════════════════════════════════════════════════════════════════════════
    CONSTANCIA SERVICE — Sistema Operativo de Confianza

    No es un chatbot. Es el registro probatorio de la relación con cada usuario:
    investiga con evidencia trazable, emite recibos firmados y compromisos
    exigibles que se cumplen solos o se compensan solos.

    Diseño: docs/DESIGN_CONSTANCIA_TRUST_OS.md (producto)
    docs/DESIGN_CONSTANCIA_ARQUITECTURA.md (ingeniería)

    Contratos que NO se pueden romper:
    1. Todo hecho que llega al usuario viaja como FactCard con procedencia.
    El motor de razonamiento nunca redacta cifras, fechas ni estados.
    2. Toda acción produce un Receipt firmado con `verify_hint`: cómo
    comprobarlo SIN nosotros.
    3. Todo compromiso lleva un verificador computable y una fecha. Si se
    incumple, la remediación se ejecuta sin que el usuario pregunte.
    4. AdjustPlan existe a propósito: la aversión al algoritmo desaparece
    cuando la persona puede MODIFICAR el resultado, no solo aceptarlo.
    5. RequestHuman nunca tiene fricción. La disposición a ser saltada es en
    sí la señal que gana la confianza.
    ═══════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenCase = channel.unary_unary(
                '/constancia.ConstanciaService/OpenCase',
                request_serializer=constancia_dot_constancia__pb2.OpenCaseRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.CaseResponse.FromString,
                _registered_method=True)
        self.GetCase = channel.unary_unary(
                '/constancia.ConstanciaService/GetCase',
                request_serializer=constancia_dot_constancia__pb2.GetCaseRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.CaseResponse.FromString,
                _registered_method=True)
        self.ListUserCases = channel.unary_unary(
                '/constancia.ConstanciaService/ListUserCases',
                request_serializer=constancia_dot_constancia__pb2.ListUserCasesRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.ListUserCasesResponse.FromString,
                _registered_method=True)
        self.AdminListCases = channel.unary_unary(
                '/constancia.ConstanciaService/AdminListCases',
                request_serializer=constancia_dot_constancia__pb2.AdminListCasesRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.AdminListCasesResponse.FromString,
                _registered_method=True)
        self.GetTrustMetrics = channel.unary_unary(
                '/constancia.ConstanciaService/GetTrustMetrics',
                request_serializer=constancia_dot_constancia__pb2.TrustMetricsRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.TrustMetricsResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/constancia.ConstanciaService/SendMessage',
                request_serializer=constancia_dot_constancia__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.CaseResponse.FromString,
                _registered_method=True)
        self.ConfirmPlan = channel.unary_unary(
                '/constancia.ConstanciaService/ConfirmPlan',
                request_serializer=constancia_dot_constancia__pb2.ConfirmPlanRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.CaseResponse.FromString,
                _registered_method=True)
        self.AdjustPlan = channel.unary_unary(
                '/constancia.ConstanciaService/AdjustPlan',
                request_serializer=constancia_dot_constancia__pb2.AdjustPlanRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.CaseResponse.FromString,
                _registered_method=True)
        self.RequestHuman = channel.unary_unary(
                '/constancia.ConstanciaService/RequestHuman',
                request_serializer=constancia_dot_constancia__pb2.RequestHumanRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.HandoffResponse.FromString,
                _registered_method=True)
        self.GetHandoffBrief = channel.unary_unary(
                '/constancia.ConstanciaService/GetHandoffBrief',
                request_serializer=constancia_dot_constancia__pb2.GetHandoffBriefRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.HandoffBrief.FromString,
                _registered_method=True)
        self.GetOpeningState = channel.unary_unary(
                '/constancia.ConstanciaService/GetOpeningState',
                request_serializer=constancia_dot_constancia__pb2.GetOpeningStateRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.OpeningState.FromString,
                _registered_method=True)
        self.GetCommitments = channel.unary_unary(
                '/constancia.ConstanciaService/GetCommitments',
                request_serializer=constancia_dot_constancia__pb2.GetCommitmentsRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.CommitmentList.FromString,
                _registered_method=True)
        self.GetReceipt = channel.unary_unary(
                '/constancia.ConstanciaService/GetReceipt',
                request_serializer=constancia_dot_constancia__pb2.GetReceiptRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.Receipt.FromString,
                _registered_method=True)
        self.VerifyReceipt = channel.unary_unary(
                '/constancia.ConstanciaService/VerifyReceipt',
                request_serializer=constancia_dot_constancia__pb2.VerifyReceiptRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.VerifyReceiptResponse.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/constancia.ConstanciaService/GetMemory',
                request_serializer=constancia_dot_constancia__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.MemoryList.FromString,
                _registered_method=True)
        self.ForgetMemory = channel.unary_unary(
                '/constancia.ConstanciaService/ForgetMemory',
                request_serializer=constancia_dot_constancia__pb2.ForgetMemoryRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.ForgetProof.FromString,
                _registered_method=True)
        self.IngestSignal = channel.unary_unary(
                '/constancia.ConstanciaService/IngestSignal',
                request_serializer=constancia_dot_constancia__pb2.IngestSignalRequest.SerializeToString,
                response_deserializer=constancia_dot_constancia__pb2.IngestSignalResponse.FromString,
                _registered_method=True)


class ConstanciaServiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════════
    CONSTANCIA SERVICE — Sistema Operativo de Confianza

    No es un chatbot. Es el registro probatorio de la relación con cada usuario:
    investiga con evidencia trazable, emite recibos firmados y compromisos
    exigibles que se cumplen solos o se compensan solos.

    Diseño: docs/DESIGN_CONSTANCIA_TRUST_OS.md (producto)
    docs/DESIGN_CONSTANCIA_ARQUITECTURA.md (ingeniería)

    Contratos que NO se pueden romper:
    1. Todo hecho que llega al usuario viaja como FactCard con procedencia.
    El motor de razonamiento nunca redacta cifras, fechas ni estados.
    2. Toda acción produce un Receipt firmado con `verify_hint`: cómo
    comprobarlo SIN nosotros.
    3. Todo compromiso lleva un verificador computable y una fecha. Si se
    incumple, la remediación se ejecuta sin que el usuario pregunte.
    4. AdjustPlan existe a propósito: la aversión al algoritmo desaparece
    cuando la persona puede MODIFICAR el resultado, no solo aceptarlo.
    5. RequestHuman nunca tiene fricción. La disposición a ser saltada es en
    sí la señal que gana la confianza.
    ═══════════════════════════════════════════════════════════════════════════

    """

    def OpenCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserCases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminListCases(self, request, context):
        """La cola del equipo. `ListUserCases` es por titular y no sirve para operar:
        un admin no tiene casos propios que mirar. Solo admin o sistema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrustMetrics(self, request, context):
        """El marcador del Sistema de Confianza. Se calcula desde las FILAS, no desde
        los contadores de Prometheus: esos se reinician con el proceso y no se
        pueden recalcular ni auditar caso por caso.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdjustPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestHuman(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHandoffBrief(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOpeningState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommitments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConstanciaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenCase': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenCase,
                    request_deserializer=constancia_dot_constancia__pb2.OpenCaseRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.CaseResponse.SerializeToString,
            ),
            'GetCase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCase,
                    request_deserializer=constancia_dot_constancia__pb2.GetCaseRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.CaseResponse.SerializeToString,
            ),
            'ListUserCases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserCases,
                    request_deserializer=constancia_dot_constancia__pb2.ListUserCasesRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.ListUserCasesResponse.SerializeToString,
            ),
            'AdminListCases': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminListCases,
                    request_deserializer=constancia_dot_constancia__pb2.AdminListCasesRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.AdminListCasesResponse.SerializeToString,
            ),
            'GetTrustMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrustMetrics,
                    request_deserializer=constancia_dot_constancia__pb2.TrustMetricsRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.TrustMetricsResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=constancia_dot_constancia__pb2.SendMessageRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.CaseResponse.SerializeToString,
            ),
            'ConfirmPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmPlan,
                    request_deserializer=constancia_dot_constancia__pb2.ConfirmPlanRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.CaseResponse.SerializeToString,
            ),
            'AdjustPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.AdjustPlan,
                    request_deserializer=constancia_dot_constancia__pb2.AdjustPlanRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.CaseResponse.SerializeToString,
            ),
            'RequestHuman': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestHuman,
                    request_deserializer=constancia_dot_constancia__pb2.RequestHumanRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.HandoffResponse.SerializeToString,
            ),
            'GetHandoffBrief': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHandoffBrief,
                    request_deserializer=constancia_dot_constancia__pb2.GetHandoffBriefRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.HandoffBrief.SerializeToString,
            ),
            'GetOpeningState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOpeningState,
                    request_deserializer=constancia_dot_constancia__pb2.GetOpeningStateRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.OpeningState.SerializeToString,
            ),
            'GetCommitments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommitments,
                    request_deserializer=constancia_dot_constancia__pb2.GetCommitmentsRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.CommitmentList.SerializeToString,
            ),
            'GetReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipt,
                    request_deserializer=constancia_dot_constancia__pb2.GetReceiptRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.Receipt.SerializeToString,
            ),
            'VerifyReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyReceipt,
                    request_deserializer=constancia_dot_constancia__pb2.VerifyReceiptRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.VerifyReceiptResponse.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=constancia_dot_constancia__pb2.GetMemoryRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.MemoryList.SerializeToString,
            ),
            'ForgetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgetMemory,
                    request_deserializer=constancia_dot_constancia__pb2.ForgetMemoryRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.ForgetProof.SerializeToString,
            ),
            'IngestSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestSignal,
                    request_deserializer=constancia_dot_constancia__pb2.IngestSignalRequest.FromString,
                    response_serializer=constancia_dot_constancia__pb2.IngestSignalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'constancia.ConstanciaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('constancia.ConstanciaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConstanciaService(object):
    """═══════════════════════════════════════════════════════════════════════════
    CONSTANCIA SERVICE — Sistema Operativo de Confianza

    No es un chatbot. Es el registro probatorio de la relación con cada usuario:
    investiga con evidencia trazable, emite recibos firmados y compromisos
    exigibles que se cumplen solos o se compensan solos.

    Diseño: docs/DESIGN_CONSTANCIA_TRUST_OS.md (producto)
    docs/DESIGN_CONSTANCIA_ARQUITECTURA.md (ingeniería)

    Contratos que NO se pueden romper:
    1. Todo hecho que llega al usuario viaja como FactCard con procedencia.
    El motor de razonamiento nunca redacta cifras, fechas ni estados.
    2. Toda acción produce un Receipt firmado con `verify_hint`: cómo
    comprobarlo SIN nosotros.
    3. Todo compromiso lleva un verificador computable y una fecha. Si se
    incumple, la remediación se ejecuta sin que el usuario pregunte.
    4. AdjustPlan existe a propósito: la aversión al algoritmo desaparece
    cuando la persona puede MODIFICAR el resultado, no solo aceptarlo.
    5. RequestHuman nunca tiene fricción. La disposición a ser saltada es en
    sí la señal que gana la confianza.
    ═══════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def OpenCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/OpenCase',
            constancia_dot_constancia__pb2.OpenCaseRequest.SerializeToString,
            constancia_dot_constancia__pb2.CaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/GetCase',
            constancia_dot_constancia__pb2.GetCaseRequest.SerializeToString,
            constancia_dot_constancia__pb2.CaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/ListUserCases',
            constancia_dot_constancia__pb2.ListUserCasesRequest.SerializeToString,
            constancia_dot_constancia__pb2.ListUserCasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminListCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/AdminListCases',
            constancia_dot_constancia__pb2.AdminListCasesRequest.SerializeToString,
            constancia_dot_constancia__pb2.AdminListCasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrustMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/GetTrustMetrics',
            constancia_dot_constancia__pb2.TrustMetricsRequest.SerializeToString,
            constancia_dot_constancia__pb2.TrustMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/SendMessage',
            constancia_dot_constancia__pb2.SendMessageRequest.SerializeToString,
            constancia_dot_constancia__pb2.CaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/ConfirmPlan',
            constancia_dot_constancia__pb2.ConfirmPlanRequest.SerializeToString,
            constancia_dot_constancia__pb2.CaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdjustPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/AdjustPlan',
            constancia_dot_constancia__pb2.AdjustPlanRequest.SerializeToString,
            constancia_dot_constancia__pb2.CaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestHuman(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/RequestHuman',
            constancia_dot_constancia__pb2.RequestHumanRequest.SerializeToString,
            constancia_dot_constancia__pb2.HandoffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHandoffBrief(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/GetHandoffBrief',
            constancia_dot_constancia__pb2.GetHandoffBriefRequest.SerializeToString,
            constancia_dot_constancia__pb2.HandoffBrief.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOpeningState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/GetOpeningState',
            constancia_dot_constancia__pb2.GetOpeningStateRequest.SerializeToString,
            constancia_dot_constancia__pb2.OpeningState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommitments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/GetCommitments',
            constancia_dot_constancia__pb2.GetCommitmentsRequest.SerializeToString,
            constancia_dot_constancia__pb2.CommitmentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/GetReceipt',
            constancia_dot_constancia__pb2.GetReceiptRequest.SerializeToString,
            constancia_dot_constancia__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/VerifyReceipt',
            constancia_dot_constancia__pb2.VerifyReceiptRequest.SerializeToString,
            constancia_dot_constancia__pb2.VerifyReceiptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/GetMemory',
            constancia_dot_constancia__pb2.GetMemoryRequest.SerializeToString,
            constancia_dot_constancia__pb2.MemoryList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/ForgetMemory',
            constancia_dot_constancia__pb2.ForgetMemoryRequest.SerializeToString,
            constancia_dot_constancia__pb2.ForgetProof.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constancia.ConstanciaService/IngestSignal',
            constancia_dot_constancia__pb2.IngestSignalRequest.SerializeToString,
            constancia_dot_constancia__pb2.IngestSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
