# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.appointment import appointment_pb2 as protos_dot_appointment_dot_appointment__pb2


class AppointmentServiceStub(object):
    """═══════════════════════════════════════════════════════════════════════════
    APPOINTMENT SERVICE

    Core business service for VeterPlan's veterinary home visits marketplace.
    Manages the full appointment lifecycle from request to completion,
    including vet matching, state machine transitions, payments, and reviews.

    Depends on: Auth, Profile, Pet, VetCertification, Payment, Geolocation,
    Notification services.
    ═══════════════════════════════════════════════════════════════════════════

    ─── LIFECYCLE ───
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAppointment = channel.unary_unary(
                '/appointment.AppointmentService/RequestAppointment',
                request_serializer=protos_dot_appointment_dot_appointment__pb2.RequestAppointmentRequest.SerializeToString,
                response_deserializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
                )
        self.AcceptAppointment = channel.unary_unary(
                '/appointment.AppointmentService/AcceptAppointment',
                request_serializer=protos_dot_appointment_dot_appointment__pb2.AcceptAppointmentRequest.SerializeToString,
                response_deserializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
                )
        self.UpdateAppointmentStatus = channel.unary_unary(
                '/appointment.AppointmentService/UpdateAppointmentStatus',
                request_serializer=protos_dot_appointment_dot_appointment__pb2.UpdateAppointmentStatusRequest.SerializeToString,
                response_deserializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
                )
        self.ConfirmArrival = channel.unary_unary(
                '/appointment.AppointmentService/ConfirmArrival',
                request_serializer=protos_dot_appointment_dot_appointment__pb2.ConfirmArrivalRequest.SerializeToString,
                response_deserializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
                )
        self.CancelAppointment = channel.unary_unary(
                '/appointment.AppointmentService/CancelAppointment',
                request_serializer=protos_dot_appointment_dot_appointment__pb2.CancelAppointmentRequest.SerializeToString,
                response_deserializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
                )
        self.GetAppointment = channel.unary_unary(
                '/appointment.AppointmentService/GetAppointment',
                request_serializer=protos_dot_appointment_dot_appointment__pb2.GetAppointmentRequest.SerializeToString,
                response_deserializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
                )
        self.GetClientAppointments = channel.unary_unary(
                '/appointment.AppointmentService/GetClientAppointments',
                request_serializer=protos_dot_appointment_dot_appointment__pb2.GetClientAppointmentsRequest.SerializeToString,
                response_deserializer=protos_dot_appointment_dot_appointment__pb2.AppointmentsResponse.FromString,
                )
        self.GetVetAppointments = channel.unary_unary(
                '/appointment.AppointmentService/GetVetAppointments',
                request_serializer=protos_dot_appointment_dot_appointment__pb2.GetVetAppointmentsRequest.SerializeToString,
                response_deserializer=protos_dot_appointment_dot_appointment__pb2.AppointmentsResponse.FromString,
                )
        self.GetAvailableVets = channel.unary_unary(
                '/appointment.AppointmentService/GetAvailableVets',
                request_serializer=protos_dot_appointment_dot_appointment__pb2.GetAvailableVetsRequest.SerializeToString,
                response_deserializer=protos_dot_appointment_dot_appointment__pb2.AvailableVetsResponse.FromString,
                )


class AppointmentServiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════════
    APPOINTMENT SERVICE

    Core business service for VeterPlan's veterinary home visits marketplace.
    Manages the full appointment lifecycle from request to completion,
    including vet matching, state machine transitions, payments, and reviews.

    Depends on: Auth, Profile, Pet, VetCertification, Payment, Geolocation,
    Notification services.
    ═══════════════════════════════════════════════════════════════════════════

    ─── LIFECYCLE ───
    """

    def RequestAppointment(self, request, context):
        """Client requests a new appointment (creates REQUESTED state)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptAppointment(self, request, context):
        """Vet accepts an appointment (REQUESTED -> ACCEPTED, first-come-first-served)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAppointmentStatus(self, request, context):
        """Update appointment status (EN_ROUTE, COMPLETED, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmArrival(self, request, context):
        """Vet confirms arrival with 6-digit PIN (ARRIVED -> IN_PROGRESS)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAppointment(self, request, context):
        """Cancel an appointment (client, vet, or system)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppointment(self, request, context):
        """─── QUERIES ───

        Get a single appointment by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientAppointments(self, request, context):
        """Get appointments for a client (with optional status filter)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVetAppointments(self, request, context):
        """Get appointments for a vet (with optional status filter)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableVets(self, request, context):
        """─── MATCHING ───

        Find available vets for a service at a location and time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppointmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAppointment,
                    request_deserializer=protos_dot_appointment_dot_appointment__pb2.RequestAppointmentRequest.FromString,
                    response_serializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'AcceptAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptAppointment,
                    request_deserializer=protos_dot_appointment_dot_appointment__pb2.AcceptAppointmentRequest.FromString,
                    response_serializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'UpdateAppointmentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAppointmentStatus,
                    request_deserializer=protos_dot_appointment_dot_appointment__pb2.UpdateAppointmentStatusRequest.FromString,
                    response_serializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'ConfirmArrival': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmArrival,
                    request_deserializer=protos_dot_appointment_dot_appointment__pb2.ConfirmArrivalRequest.FromString,
                    response_serializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'CancelAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAppointment,
                    request_deserializer=protos_dot_appointment_dot_appointment__pb2.CancelAppointmentRequest.FromString,
                    response_serializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'GetAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppointment,
                    request_deserializer=protos_dot_appointment_dot_appointment__pb2.GetAppointmentRequest.FromString,
                    response_serializer=protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'GetClientAppointments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientAppointments,
                    request_deserializer=protos_dot_appointment_dot_appointment__pb2.GetClientAppointmentsRequest.FromString,
                    response_serializer=protos_dot_appointment_dot_appointment__pb2.AppointmentsResponse.SerializeToString,
            ),
            'GetVetAppointments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVetAppointments,
                    request_deserializer=protos_dot_appointment_dot_appointment__pb2.GetVetAppointmentsRequest.FromString,
                    response_serializer=protos_dot_appointment_dot_appointment__pb2.AppointmentsResponse.SerializeToString,
            ),
            'GetAvailableVets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableVets,
                    request_deserializer=protos_dot_appointment_dot_appointment__pb2.GetAvailableVetsRequest.FromString,
                    response_serializer=protos_dot_appointment_dot_appointment__pb2.AvailableVetsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appointment.AppointmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppointmentService(object):
    """═══════════════════════════════════════════════════════════════════════════
    APPOINTMENT SERVICE

    Core business service for VeterPlan's veterinary home visits marketplace.
    Manages the full appointment lifecycle from request to completion,
    including vet matching, state machine transitions, payments, and reviews.

    Depends on: Auth, Profile, Pet, VetCertification, Payment, Geolocation,
    Notification services.
    ═══════════════════════════════════════════════════════════════════════════

    ─── LIFECYCLE ───
    """

    @staticmethod
    def RequestAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/RequestAppointment',
            protos_dot_appointment_dot_appointment__pb2.RequestAppointmentRequest.SerializeToString,
            protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/AcceptAppointment',
            protos_dot_appointment_dot_appointment__pb2.AcceptAppointmentRequest.SerializeToString,
            protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAppointmentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/UpdateAppointmentStatus',
            protos_dot_appointment_dot_appointment__pb2.UpdateAppointmentStatusRequest.SerializeToString,
            protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmArrival(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/ConfirmArrival',
            protos_dot_appointment_dot_appointment__pb2.ConfirmArrivalRequest.SerializeToString,
            protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/CancelAppointment',
            protos_dot_appointment_dot_appointment__pb2.CancelAppointmentRequest.SerializeToString,
            protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/GetAppointment',
            protos_dot_appointment_dot_appointment__pb2.GetAppointmentRequest.SerializeToString,
            protos_dot_appointment_dot_appointment__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClientAppointments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/GetClientAppointments',
            protos_dot_appointment_dot_appointment__pb2.GetClientAppointmentsRequest.SerializeToString,
            protos_dot_appointment_dot_appointment__pb2.AppointmentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVetAppointments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/GetVetAppointments',
            protos_dot_appointment_dot_appointment__pb2.GetVetAppointmentsRequest.SerializeToString,
            protos_dot_appointment_dot_appointment__pb2.AppointmentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableVets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/GetAvailableVets',
            protos_dot_appointment_dot_appointment__pb2.GetAvailableVetsRequest.SerializeToString,
            protos_dot_appointment_dot_appointment__pb2.AvailableVetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
