# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from medhistory import medhistory_pb2 as medhistory_dot_medhistory__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in medhistory/medhistory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MedHistoryServiceStub(object):
    """═══════════════════════════════════════════════════════════════════════════
    MEDHISTORY SERVICE — Registro Clínico Estructurado (Fase 1)

    Fuente de verdad del encuentro clínico a domicilio. pets-service mantiene el
    "carné actual" (peso, alergias, próxima vacuna) como PROYECCIÓN que este
    servicio actualiza al finalizar el registro.

    Diseño: medhistory-service/DESIGN_FASE1_REGISTRO_CLINICO.md
    Depends on: Appointment (appointment_id), Pet (pet_id), Profile (vet/client),
    VetCertification (ValidateCanPractice), Files (adjuntos)

    Contratos a prueba de Fases 2-3 (§13 del diseño) — NO removerlos:
    1. Clave estable `bloque.campo` + template exportable como JSON Schema
    2. Procedencia y confianza por campo (FieldMeta)
    3. Update con semántica de patch por ruta + revisión (concurrencia optimista)
    4. Evento por patch a pubsub `consultation:{id}`
    5. Flag client_visible por bloque/campo
    6. Anexo de captura cruda (audio + transcripción)
    ═══════════════════════════════════════════════════════════════════════════

    ─── TEMPLATE ───
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConsultationTemplate = channel.unary_unary(
                '/medhistory.MedHistoryService/GetConsultationTemplate',
                request_serializer=medhistory_dot_medhistory__pb2.GetConsultationTemplateRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.ConsultationTemplateResponse.FromString,
                _registered_method=True)
        self.GetReferenceData = channel.unary_unary(
                '/medhistory.MedHistoryService/GetReferenceData',
                request_serializer=medhistory_dot_medhistory__pb2.GetReferenceDataRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.GetReferenceDataResponse.FromString,
                _registered_method=True)
        self.StartConsultationRecord = channel.unary_unary(
                '/medhistory.MedHistoryService/StartConsultationRecord',
                request_serializer=medhistory_dot_medhistory__pb2.StartConsultationRecordRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.ConsultationRecordResponse.FromString,
                _registered_method=True)
        self.UpdateConsultationRecord = channel.unary_unary(
                '/medhistory.MedHistoryService/UpdateConsultationRecord',
                request_serializer=medhistory_dot_medhistory__pb2.UpdateConsultationRecordRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.UpdateConsultationRecordResponse.FromString,
                _registered_method=True)
        self.MarkPendingFinalization = channel.unary_unary(
                '/medhistory.MedHistoryService/MarkPendingFinalization',
                request_serializer=medhistory_dot_medhistory__pb2.MarkPendingFinalizationRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.ConsultationRecordResponse.FromString,
                _registered_method=True)
        self.FinalizeConsultationRecord = channel.unary_unary(
                '/medhistory.MedHistoryService/FinalizeConsultationRecord',
                request_serializer=medhistory_dot_medhistory__pb2.FinalizeConsultationRecordRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.FinalizeConsultationRecordResponse.FromString,
                _registered_method=True)
        self.AmendConsultationRecord = channel.unary_unary(
                '/medhistory.MedHistoryService/AmendConsultationRecord',
                request_serializer=medhistory_dot_medhistory__pb2.AmendConsultationRecordRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.ConsultationRecordResponse.FromString,
                _registered_method=True)
        self.GetConsultationRecord = channel.unary_unary(
                '/medhistory.MedHistoryService/GetConsultationRecord',
                request_serializer=medhistory_dot_medhistory__pb2.GetConsultationRecordRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.ConsultationRecordResponse.FromString,
                _registered_method=True)
        self.GetPetMedicalHistory = channel.unary_unary(
                '/medhistory.MedHistoryService/GetPetMedicalHistory',
                request_serializer=medhistory_dot_medhistory__pb2.GetPetMedicalHistoryRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.GetPetMedicalHistoryResponse.FromString,
                _registered_method=True)
        self.ExportConsultationSOAP = channel.unary_unary(
                '/medhistory.MedHistoryService/ExportConsultationSOAP',
                request_serializer=medhistory_dot_medhistory__pb2.ExportConsultationSOAPRequest.SerializeToString,
                response_deserializer=medhistory_dot_medhistory__pb2.ExportConsultationSOAPResponse.FromString,
                _registered_method=True)


class MedHistoryServiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════════
    MEDHISTORY SERVICE — Registro Clínico Estructurado (Fase 1)

    Fuente de verdad del encuentro clínico a domicilio. pets-service mantiene el
    "carné actual" (peso, alergias, próxima vacuna) como PROYECCIÓN que este
    servicio actualiza al finalizar el registro.

    Diseño: medhistory-service/DESIGN_FASE1_REGISTRO_CLINICO.md
    Depends on: Appointment (appointment_id), Pet (pet_id), Profile (vet/client),
    VetCertification (ValidateCanPractice), Files (adjuntos)

    Contratos a prueba de Fases 2-3 (§13 del diseño) — NO removerlos:
    1. Clave estable `bloque.campo` + template exportable como JSON Schema
    2. Procedencia y confianza por campo (FieldMeta)
    3. Update con semántica de patch por ruta + revisión (concurrencia optimista)
    4. Evento por patch a pubsub `consultation:{id}`
    5. Flag client_visible por bloque/campo
    6. Anexo de captura cruda (audio + transcripción)
    ═══════════════════════════════════════════════════════════════════════════

    ─── TEMPLATE ───
    """

    def GetConsultationTemplate(self, request, context):
        """Devuelve el esquema de bloques (receta) para un ServiceType + especie.
        La app arma el formulario con esto. Exportable como JSON Schema para
        alimentar a la IA de Fase 2 como definición de herramienta.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReferenceData(self, request, context):
        """Devuelve el contenido de una tabla de referencia (catálogo de vacunas,
        rangos de vitales, hallazgos por sistema, etc.). Es lo que llena los
        desplegables que el template declara en `reference_table`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartConsultationRecord(self, request, context):
        """─── CICLO DE VIDA DEL REGISTRO ───

        Abre el borrador al entrar a IN_PROGRESS (llamado por appointment-service).
        Idempotente: si ya existe un registro para el appointment, lo devuelve.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConsultationRecord(self, request, context):
        """Autosave parcial mientras el registro es borrador. Semántica de PATCH por
        ruta de campo — nunca reemplaza el registro completo (contrato §13.3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkPendingFinalization(self, request, context):
        """Llamado por appointment-service cuando la cita pasa a COMPLETED.
        Mueve el registro a PENDING_FINALIZATION y arranca la ventana de 24-48h.
        Exige solo el mínimo (registro iniciado) para no trabar el cobro.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeConsultationRecord(self, request, context):
        """Valida los bloques requeridos de la receta, dispara los side-effects vía
        outbox transaccional y bloquea el registro.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AmendConsultationRecord(self, request, context):
        """Corrección post-cierre. Append-only con justificación y traza (legal).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsultationRecord(self, request, context):
        """─── LECTURA (control de acceso por engagement) ───

        Lectura por id o por appointment_id. Auditada.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPetMedicalHistory(self, request, context):
        """Timeline longitudinal del pet + tendencia de vitales. Un pet a la vez,
        nunca listado buscable (guardrail anti-fuga §8).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportConsultationSOAP(self, request, context):
        """Vista/PDF SOAP generada desde los datos estructurados.
        SOAP es SOLO exportación, nunca UI de captura.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedHistoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConsultationTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsultationTemplate,
                    request_deserializer=medhistory_dot_medhistory__pb2.GetConsultationTemplateRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.ConsultationTemplateResponse.SerializeToString,
            ),
            'GetReferenceData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReferenceData,
                    request_deserializer=medhistory_dot_medhistory__pb2.GetReferenceDataRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.GetReferenceDataResponse.SerializeToString,
            ),
            'StartConsultationRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.StartConsultationRecord,
                    request_deserializer=medhistory_dot_medhistory__pb2.StartConsultationRecordRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.ConsultationRecordResponse.SerializeToString,
            ),
            'UpdateConsultationRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConsultationRecord,
                    request_deserializer=medhistory_dot_medhistory__pb2.UpdateConsultationRecordRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.UpdateConsultationRecordResponse.SerializeToString,
            ),
            'MarkPendingFinalization': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkPendingFinalization,
                    request_deserializer=medhistory_dot_medhistory__pb2.MarkPendingFinalizationRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.ConsultationRecordResponse.SerializeToString,
            ),
            'FinalizeConsultationRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeConsultationRecord,
                    request_deserializer=medhistory_dot_medhistory__pb2.FinalizeConsultationRecordRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.FinalizeConsultationRecordResponse.SerializeToString,
            ),
            'AmendConsultationRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AmendConsultationRecord,
                    request_deserializer=medhistory_dot_medhistory__pb2.AmendConsultationRecordRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.ConsultationRecordResponse.SerializeToString,
            ),
            'GetConsultationRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsultationRecord,
                    request_deserializer=medhistory_dot_medhistory__pb2.GetConsultationRecordRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.ConsultationRecordResponse.SerializeToString,
            ),
            'GetPetMedicalHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPetMedicalHistory,
                    request_deserializer=medhistory_dot_medhistory__pb2.GetPetMedicalHistoryRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.GetPetMedicalHistoryResponse.SerializeToString,
            ),
            'ExportConsultationSOAP': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportConsultationSOAP,
                    request_deserializer=medhistory_dot_medhistory__pb2.ExportConsultationSOAPRequest.FromString,
                    response_serializer=medhistory_dot_medhistory__pb2.ExportConsultationSOAPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'medhistory.MedHistoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('medhistory.MedHistoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MedHistoryService(object):
    """═══════════════════════════════════════════════════════════════════════════
    MEDHISTORY SERVICE — Registro Clínico Estructurado (Fase 1)

    Fuente de verdad del encuentro clínico a domicilio. pets-service mantiene el
    "carné actual" (peso, alergias, próxima vacuna) como PROYECCIÓN que este
    servicio actualiza al finalizar el registro.

    Diseño: medhistory-service/DESIGN_FASE1_REGISTRO_CLINICO.md
    Depends on: Appointment (appointment_id), Pet (pet_id), Profile (vet/client),
    VetCertification (ValidateCanPractice), Files (adjuntos)

    Contratos a prueba de Fases 2-3 (§13 del diseño) — NO removerlos:
    1. Clave estable `bloque.campo` + template exportable como JSON Schema
    2. Procedencia y confianza por campo (FieldMeta)
    3. Update con semántica de patch por ruta + revisión (concurrencia optimista)
    4. Evento por patch a pubsub `consultation:{id}`
    5. Flag client_visible por bloque/campo
    6. Anexo de captura cruda (audio + transcripción)
    ═══════════════════════════════════════════════════════════════════════════

    ─── TEMPLATE ───
    """

    @staticmethod
    def GetConsultationTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/GetConsultationTemplate',
            medhistory_dot_medhistory__pb2.GetConsultationTemplateRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.ConsultationTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReferenceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/GetReferenceData',
            medhistory_dot_medhistory__pb2.GetReferenceDataRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.GetReferenceDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartConsultationRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/StartConsultationRecord',
            medhistory_dot_medhistory__pb2.StartConsultationRecordRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.ConsultationRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConsultationRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/UpdateConsultationRecord',
            medhistory_dot_medhistory__pb2.UpdateConsultationRecordRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.UpdateConsultationRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkPendingFinalization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/MarkPendingFinalization',
            medhistory_dot_medhistory__pb2.MarkPendingFinalizationRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.ConsultationRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeConsultationRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/FinalizeConsultationRecord',
            medhistory_dot_medhistory__pb2.FinalizeConsultationRecordRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.FinalizeConsultationRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AmendConsultationRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/AmendConsultationRecord',
            medhistory_dot_medhistory__pb2.AmendConsultationRecordRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.ConsultationRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsultationRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/GetConsultationRecord',
            medhistory_dot_medhistory__pb2.GetConsultationRecordRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.ConsultationRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPetMedicalHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/GetPetMedicalHistory',
            medhistory_dot_medhistory__pb2.GetPetMedicalHistoryRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.GetPetMedicalHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportConsultationSOAP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medhistory.MedHistoryService/ExportConsultationSOAP',
            medhistory_dot_medhistory__pb2.ExportConsultationSOAPRequest.SerializeToString,
            medhistory_dot_medhistory__pb2.ExportConsultationSOAPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
